<?php

return [

    'brand' => [
        'name' => 'Agricart ERP',
    ],

    'dashboard' => [
        'label' => 'Dashboard',
        'submenus' => [
            'overview' => 'Overview',
        ],
    ],

    'modules' => [
        'approvals' => [
            'label' => 'Approvals',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedClipboardDocumentCheck,
            'sort' => 10,
            'categories' => [
                'overview' => [
                    'label' => 'Overview',
                ],
                'contacts' => [
                    'label' => 'Contacts',
                    'types' => [
                        'suppliers' => 'Suppliers',
                        'customers' => 'Customers',
                    ],
                ],
                'product-catalog' => [
                    'label' => 'Product Catalog',
                    'types' => [
                        'categories' => 'Categories',
                        'brands' => 'Brands',
                        'units' => 'Units',
                        'attributes' => 'Attributes',
                        'controls' => 'Controls',
                        'products' => 'Products',
                    ],
                ],
                'staff' => [
                    'label' => 'Staff',
                    'types' => [
                        'users' => 'Users',
                        'leaves' => 'Leaves',
                    ],
                ],
                'sales' => [
                    'label' => 'Sales',
                    'types' => [
                        'quotations' => 'Quotations',
                        'returns' => 'Returns',
                    ],
                ],
                'purchasing' => [
                    'label' => 'Purchasing',
                    'types' => [
                        'quotations' => 'Quotations',
                        're-orders' => 'Re-Orders',
                    ],
                ],
                'finance' => [
                    'label' => 'Finance',
                    'types' => [
                        'expenses' => 'Expenses',
                        'advances' => 'Advances',
                    ],
                ],
            ],
            'category_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'contacts' => \Filament\Support\Icons\Heroicon::OutlinedUserGroup,
                'product-catalog' => \Filament\Support\Icons\Heroicon::OutlinedCube,
                'staff' => \Filament\Support\Icons\Heroicon::OutlinedUsers,
                'sales' => \Filament\Support\Icons\Heroicon::OutlinedShoppingCart,
                'purchasing' => \Filament\Support\Icons\Heroicon::OutlinedTruck,
                'finance' => \Filament\Support\Icons\Heroicon::OutlinedBanknotes,
            ],
            'type_icons' => [
                'contacts' => [
                    'suppliers' => \Filament\Support\Icons\Heroicon::OutlinedBuildingStorefront,
                    'customers' => \Filament\Support\Icons\Heroicon::OutlinedUserGroup,
                ],
                'product-catalog' => [
                    'categories' => \Filament\Support\Icons\Heroicon::OutlinedRectangleStack,
                    'brands' => \Filament\Support\Icons\Heroicon::OutlinedTag,
                    'units' => \Filament\Support\Icons\Heroicon::OutlinedScale,
                    'attributes' => \Filament\Support\Icons\Heroicon::OutlinedAdjustmentsHorizontal,
                    'controls' => \Filament\Support\Icons\Heroicon::OutlinedShieldCheck,
                    'products' => \Filament\Support\Icons\Heroicon::OutlinedCube,
                ],
                'staff' => [
                    'users' => \Filament\Support\Icons\Heroicon::OutlinedUsers,
                    'leaves' => \Filament\Support\Icons\Heroicon::OutlinedCalendarDays,
                ],
                'sales' => [
                    'quotations' => \Filament\Support\Icons\Heroicon::OutlinedDocumentText,
                    'returns' => \Filament\Support\Icons\Heroicon::OutlinedArrowUturnLeft,
                ],
                'purchasing' => [
                    'quotations' => \Filament\Support\Icons\Heroicon::OutlinedDocumentText,
                    're-orders' => \Filament\Support\Icons\Heroicon::OutlinedArrowPath,
                ],
                'finance' => [
                    'expenses' => \Filament\Support\Icons\Heroicon::OutlinedReceiptPercent,
                    'advances' => \Filament\Support\Icons\Heroicon::OutlinedBanknotes,
                ],
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\Approvals\Overview::class,
                'contacts.suppliers' => \App\Filament\Pages\Approvals\Contacts\Suppliers::class,
                'contacts.customers' => \App\Filament\Pages\Approvals\Contacts\Customers::class,
                'product-catalog.categories' => \App\Filament\Pages\Approvals\ProductCatalog\Categories::class,
                'product-catalog.brands' => \App\Filament\Pages\Approvals\ProductCatalog\Brands::class,
                'product-catalog.units' => \App\Filament\Pages\Approvals\ProductCatalog\Units::class,
                'product-catalog.attributes' => \App\Filament\Pages\Approvals\ProductCatalog\Attributes::class,
                'product-catalog.controls' => \App\Filament\Pages\Approvals\ProductCatalog\Controls::class,
                'product-catalog.products' => \App\Filament\Pages\Approvals\ProductCatalog\Products::class,
                'staff.users' => \App\Filament\Pages\Approvals\Staff\Users::class,
                'staff.leaves' => \App\Filament\Pages\Approvals\Staff\Leaves::class,
                'sales.quotations' => \App\Filament\Pages\Approvals\Sales\Quotations::class,
                'sales.returns' => \App\Filament\Pages\Approvals\Sales\Returns::class,
                'purchasing.quotations' => \App\Filament\Pages\Approvals\Purchasing\Quotations::class,
                'purchasing.re-orders' => \App\Filament\Pages\Approvals\Purchasing\ReOrders::class,
                'finance.expenses' => \App\Filament\Pages\Approvals\Finance\Expenses::class,
                'finance.advances' => \App\Filament\Pages\Approvals\Finance\Advances::class,
            ],
        ],
        'contacts' => [
            'label' => 'Contacts',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedUserGroup,
            'sort' => 20,
            'submenus' => [
                'overview' => 'Contact Overview',
                'suppliers' => 'Suppliers',
                'customers' => 'Customers',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'suppliers' => \Filament\Support\Icons\Heroicon::OutlinedBuildingStorefront,
                'customers' => \Filament\Support\Icons\Heroicon::OutlinedUserGroup,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\Contacts\ContactOverview::class,
                'suppliers' => \App\Filament\Pages\Contacts\Suppliers::class,
                'customers' => \App\Filament\Pages\Contacts\Customers::class,
            ],
        ],
        'product-catalog' => [
            'label' => 'Product Catalog',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedCube,
            'sort' => 30,
            'submenus' => [
                'overview' => 'Overview',
                'products' => 'Products',
                'categories' => 'Categories',
                'brands' => 'Brands',
                'units' => 'Units',
                'attributes' => 'Attributes',
                'controls' => 'Controls',
                'labels' => 'Labels',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'products' => \Filament\Support\Icons\Heroicon::OutlinedCube,
                'categories' => \Filament\Support\Icons\Heroicon::OutlinedRectangleStack,
                'brands' => \Filament\Support\Icons\Heroicon::OutlinedTag,
                'units' => \Filament\Support\Icons\Heroicon::OutlinedScale,
                'attributes' => \Filament\Support\Icons\Heroicon::OutlinedAdjustmentsHorizontal,
                'controls' => \Filament\Support\Icons\Heroicon::OutlinedShieldCheck,
                'labels' => \Filament\Support\Icons\Heroicon::OutlinedTicket,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\ProductCatalog\Overview::class,
                'products' => \App\Filament\Pages\ProductCatalog\Products::class,
                'categories' => \App\Filament\Pages\ProductCatalog\Categories::class,
                'brands' => \App\Filament\Pages\ProductCatalog\Brands::class,
                'units' => \App\Filament\Pages\ProductCatalog\Units::class,
                'attributes' => \App\Filament\Pages\ProductCatalog\Attributes::class,
                'controls' => \App\Filament\Pages\ProductCatalog\Controls::class,
                'labels' => \App\Filament\Pages\ProductCatalog\Labels::class,
            ],
        ],
        'purchasing-inventory' => [
            'label' => 'Purchasing & Inventory',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedArchiveBox,
            'sort' => 40,
            'submenus' => [
                'overview' => 'Overview',
                'purchase-planning' => 'Purchase Planning',
                'purchase-quotations' => 'Purchase Quotations',
                'purchases' => 'Purchases',
                'purchase-payment-sheet' => 'Purchase Payment Sheet',
                're-order-center' => 'Re-Order Center',
                'price-tags' => 'Price Tags',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'purchase-planning' => \Filament\Support\Icons\Heroicon::OutlinedClipboardDocumentList,
                'purchase-quotations' => \Filament\Support\Icons\Heroicon::OutlinedDocumentText,
                'purchases' => \Filament\Support\Icons\Heroicon::OutlinedTruck,
                'purchase-payment-sheet' => \Filament\Support\Icons\Heroicon::OutlinedBanknotes,
                're-order-center' => \Filament\Support\Icons\Heroicon::OutlinedArrowPath,
                'price-tags' => \Filament\Support\Icons\Heroicon::OutlinedTag,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\PurchasingInventory\Overview::class,
                'purchase-planning' => \App\Filament\Pages\PurchasingInventory\PurchasePlanning::class,
                'purchase-quotations' => \App\Filament\Pages\PurchasingInventory\PurchaseQuotations::class,
                'purchases' => \App\Filament\Pages\PurchasingInventory\Purchases::class,
                'purchase-payment-sheet' => \App\Filament\Pages\PurchasingInventory\PurchasePaymentSheet::class,
                're-order-center' => \App\Filament\Pages\PurchasingInventory\ReOrderCenter::class,
                'price-tags' => \App\Filament\Pages\PurchasingInventory\PriceTags::class,
            ],
        ],
        'sales-pos' => [
            'label' => 'Sales & POS',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedShoppingCart,
            'sort' => 50,
            'submenus' => [
                'overview' => 'Overview',
                'pos-sales' => 'POS Sales',
                'held-sales' => 'Held Sales',
                'online-orders' => 'Online Orders',
                'sales-quotations' => 'Sales Quotations',
                'sales-returns' => 'Sales Returns',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'pos-sales' => \Filament\Support\Icons\Heroicon::OutlinedComputerDesktop,
                'held-sales' => \Filament\Support\Icons\Heroicon::OutlinedPauseCircle,
                'online-orders' => \Filament\Support\Icons\Heroicon::OutlinedGlobeAlt,
                'sales-quotations' => \Filament\Support\Icons\Heroicon::OutlinedDocumentText,
                'sales-returns' => \Filament\Support\Icons\Heroicon::OutlinedArrowUturnLeft,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\SalesPos\Overview::class,
                'pos-sales' => \App\Filament\Pages\SalesPos\PosSales::class,
                'held-sales' => \App\Filament\Pages\SalesPos\HeldSales::class,
                'online-orders' => \App\Filament\Pages\SalesPos\OnlineOrders::class,
                'sales-quotations' => \App\Filament\Pages\SalesPos\SalesQuotations::class,
                'sales-returns' => \App\Filament\Pages\SalesPos\SalesReturns::class,
            ],
        ],
        'online-store' => [
            'label' => 'Online Store',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedGlobeAlt,
            'sort' => 52,
            'submenus' => [
                'overview' => 'Overview',
                'api' => 'API',
                'sales-channels' => 'Sales Channels',
                'homepage-builder' => 'Homepage Builder',
                'menu-manager' => 'Menu Manager',
                'banner-manager' => 'Banner Manager',
                'pages' => 'Pages',
                'store-navigation' => 'Store Navigation',
                'theme-settings' => 'Store Front',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'api' => \Filament\Support\Icons\Heroicon::OutlinedCloud,
                'sales-channels' => \Filament\Support\Icons\Heroicon::OutlinedShoppingBag,
                'homepage-builder' => \Filament\Support\Icons\Heroicon::OutlinedHomeModern,
                'menu-manager' => \Filament\Support\Icons\Heroicon::OutlinedBars3,
                'banner-manager' => \Filament\Support\Icons\Heroicon::OutlinedPhoto,
                'pages' => \Filament\Support\Icons\Heroicon::OutlinedDocumentText,
                'store-navigation' => \Filament\Support\Icons\Heroicon::OutlinedMap,
                'theme-settings' => \Filament\Support\Icons\Heroicon::OutlinedSwatch,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\OnlineStore\Overview::class,
                'api' => \App\Filament\Pages\OnlineStore\StoreApi::class,
                'sales-channels' => \App\Filament\Pages\OnlineStore\SalesChannels::class,
                'homepage-builder' => \App\Filament\Pages\OnlineStore\HomepageBuilder::class,
                'menu-manager' => \App\Filament\Pages\OnlineStore\MenuManager::class,
                'banner-manager' => \App\Filament\Pages\OnlineStore\BannerManager::class,
                'pages' => \App\Filament\Pages\OnlineStore\StorePages::class,
                'store-navigation' => \App\Filament\Pages\OnlineStore\StoreNavigation::class,
                'theme-settings' => \App\Filament\Pages\OnlineStore\ThemeSettings::class,
            ],
        ],
        'logistics' => [
            'label' => 'Logistics',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedTruck,
            'sort' => 55,
            'submenus' => [
                'overview' => 'Overview',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\Logistics\Overview::class,
            ],
        ],
        'service-center' => [
            'label' => 'Service Center',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedWrenchScrewdriver,
            'sort' => 56,
            'submenus' => [
                'overview' => 'Overview',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\ServiceCenter\Overview::class,
            ],
        ],
        'reports-analytics' => [
            'label' => 'Reports & Analytics',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedChartBar,
            'sort' => 60,
            'submenus' => [
                'overview' => 'Overview',
                'stock-report' => 'Stock Report',
                'customer-ledger' => 'Customer Ledger',
                'supplier-ledger' => 'Supplier Ledger',
                'sales-summary' => 'Sales Summary',
                'profit-and-loss' => 'Profit & Loss',
                'expense-report' => 'Expense Report',
                'cash-report' => 'Cash Report',
                'seasonal-sales' => 'Seasonal Sales',
                'seasonal-purchases' => 'Seasonal Purchases',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'stock-report' => \Filament\Support\Icons\Heroicon::OutlinedArchiveBox,
                'customer-ledger' => \Filament\Support\Icons\Heroicon::OutlinedUserGroup,
                'supplier-ledger' => \Filament\Support\Icons\Heroicon::OutlinedBuildingStorefront,
                'sales-summary' => \Filament\Support\Icons\Heroicon::OutlinedChartBar,
                'profit-and-loss' => \Filament\Support\Icons\Heroicon::OutlinedCalculator,
                'expense-report' => \Filament\Support\Icons\Heroicon::OutlinedReceiptPercent,
                'cash-report' => \Filament\Support\Icons\Heroicon::OutlinedBanknotes,
                'seasonal-sales' => \Filament\Support\Icons\Heroicon::OutlinedPresentationChartLine,
                'seasonal-purchases' => \Filament\Support\Icons\Heroicon::OutlinedPresentationChartBar,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\ReportsAnalytics\Overview::class,
                'stock-report' => \App\Filament\Pages\ReportsAnalytics\StockReport::class,
                'customer-ledger' => \App\Filament\Pages\ReportsAnalytics\CustomerLedger::class,
                'supplier-ledger' => \App\Filament\Pages\ReportsAnalytics\SupplierLedger::class,
                'sales-summary' => \App\Filament\Pages\ReportsAnalytics\SalesSummary::class,
                'profit-and-loss' => \App\Filament\Pages\ReportsAnalytics\ProfitAndLoss::class,
                'expense-report' => \App\Filament\Pages\ReportsAnalytics\ExpenseReport::class,
                'cash-report' => \App\Filament\Pages\ReportsAnalytics\CashReport::class,
                'seasonal-sales' => \App\Filament\Pages\ReportsAnalytics\SeasonalSales::class,
                'seasonal-purchases' => \App\Filament\Pages\ReportsAnalytics\SeasonalPurchases::class,
            ],
        ],
        'staff-management' => [
            'label' => 'Staff Management',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedUsers,
            'sort' => 70,
            'submenus' => [
                'overview' => 'Overview',
                'staff' => 'Staff',
                'attendance' => 'Attendance',
                'leave-management' => 'Leave Management',
                'advances' => 'Advances',
                'payroll' => 'Payroll',
                'staff-reports' => 'Staff Reports',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'staff' => \Filament\Support\Icons\Heroicon::OutlinedUsers,
                'attendance' => \Filament\Support\Icons\Heroicon::OutlinedClock,
                'leave-management' => \Filament\Support\Icons\Heroicon::OutlinedCalendarDays,
                'advances' => \Filament\Support\Icons\Heroicon::OutlinedBanknotes,
                'payroll' => \Filament\Support\Icons\Heroicon::OutlinedCalculator,
                'staff-reports' => \Filament\Support\Icons\Heroicon::OutlinedDocumentChartBar,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\StaffManagement\Overview::class,
                'staff' => \App\Filament\Pages\StaffManagement\Staff::class,
                'attendance' => \App\Filament\Pages\StaffManagement\Attendance::class,
                'leave-management' => \App\Filament\Pages\StaffManagement\LeaveManagement::class,
                'advances' => \App\Filament\Pages\StaffManagement\Advances::class,
                'payroll' => \App\Filament\Pages\StaffManagement\Payroll::class,
                'staff-reports' => \App\Filament\Pages\StaffManagement\StaffReports::class,
            ],
        ],
        'finance-accounts' => [
            'label' => 'Finance & Accounts',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedBanknotes,
            'sort' => 90,
            'submenus' => [
                'overview' => 'Overview',
                'expense-categories' => 'Expense Categories',
                'expenses' => 'Expenses',
                'cash-book' => 'Cash Book',
                'bank-accounts' => 'Bank Accounts',
                'cash-bank-transfers' => 'Cash & Bank Transfers',
                'financial-reports' => 'Financial Reports',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'expense-categories' => \Filament\Support\Icons\Heroicon::OutlinedRectangleStack,
                'expenses' => \Filament\Support\Icons\Heroicon::OutlinedReceiptPercent,
                'cash-book' => \Filament\Support\Icons\Heroicon::OutlinedBookOpen,
                'bank-accounts' => \Filament\Support\Icons\Heroicon::OutlinedBuildingLibrary,
                'cash-bank-transfers' => \Filament\Support\Icons\Heroicon::OutlinedArrowsRightLeft,
                'financial-reports' => \Filament\Support\Icons\Heroicon::OutlinedDocumentChartBar,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\FinanceAccounts\Overview::class,
                'expense-categories' => \App\Filament\Pages\FinanceAccounts\ExpenseCategories::class,
                'expenses' => \App\Filament\Pages\FinanceAccounts\Expenses::class,
                'cash-book' => \App\Filament\Pages\FinanceAccounts\CashBook::class,
                'bank-accounts' => \App\Filament\Pages\FinanceAccounts\BankAccounts::class,
                'cash-bank-transfers' => \App\Filament\Pages\FinanceAccounts\CashBankTransfers::class,
                'financial-reports' => \App\Filament\Pages\FinanceAccounts\FinancialReports::class,
            ],
        ],
        'marketplace' => [
            'label' => 'Marketplace',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedGlobeAmericas,
            'sort' => 95,
            'submenus' => [
                'overview' => 'Overview',
                'channel-connections' => 'Channel Connections',
                'product-sync' => 'Product Sync',
                'orders-sync' => 'Orders Sync',
                'pricing-rules' => 'Pricing Rules',
                'sync-logs' => 'Sync Logs',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'channel-connections' => \Filament\Support\Icons\Heroicon::OutlinedLink,
                'product-sync' => \Filament\Support\Icons\Heroicon::OutlinedArrowPath,
                'orders-sync' => \Filament\Support\Icons\Heroicon::OutlinedShoppingBag,
                'pricing-rules' => \Filament\Support\Icons\Heroicon::OutlinedTag,
                'sync-logs' => \Filament\Support\Icons\Heroicon::OutlinedClipboardDocumentList,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\Marketplace\Overview::class,
                'channel-connections' => \App\Filament\Pages\Marketplace\ChannelConnections::class,
                'product-sync' => \App\Filament\Pages\Marketplace\ProductSync::class,
                'orders-sync' => \App\Filament\Pages\Marketplace\OrdersSync::class,
                'pricing-rules' => \App\Filament\Pages\Marketplace\PricingRules::class,
                'sync-logs' => \App\Filament\Pages\Marketplace\SyncLogs::class,
            ],
        ],
        'settings' => [
            'label' => 'Settings',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedCog6Tooth,
            'sort' => 100,
            'submenus' => [
                'overview' => 'Overview',
                'general-settings' => 'Store Setting',
                'tax-system' => 'Tax System',
                'purchase-pricing' => 'Purchase Pricing',
                'ai-configuration' => 'AI Settings',
                'ai-enrichment-logs' => 'AI Logs',
                'universal-printing' => 'Printing',
                'system' => 'System',
                'roles-permissions' => 'Permission',
                'users' => 'Users',
                'system-backups' => 'Backups',
            ],
            'submenu_icons' => [
                'overview' => \Filament\Support\Icons\Heroicon::OutlinedSquares2x2,
                'general-settings' => \Filament\Support\Icons\Heroicon::OutlinedCog6Tooth,
                'tax-system' => \Filament\Support\Icons\Heroicon::OutlinedReceiptPercent,
                'purchase-pricing' => \Filament\Support\Icons\Heroicon::OutlinedCurrencyDollar,
                'ai-configuration' => \Filament\Support\Icons\Heroicon::OutlinedSparkles,
                'ai-enrichment-logs' => \Filament\Support\Icons\Heroicon::OutlinedExclamationTriangle,
                'universal-printing' => \Filament\Support\Icons\Heroicon::OutlinedPrinter,
                'system' => \Filament\Support\Icons\Heroicon::OutlinedServer,
                'roles-permissions' => \Filament\Support\Icons\Heroicon::OutlinedShieldCheck,
                'users' => \Filament\Support\Icons\Heroicon::OutlinedUsers,
                'system-backups' => \Filament\Support\Icons\Heroicon::OutlinedArchiveBoxArrowDown,
            ],
            'pages' => [
                'overview' => \App\Filament\Pages\Settings\Overview::class,
                'general-settings' => \App\Filament\Pages\Settings\GeneralSettings::class,
                'tax-system' => \App\Filament\Pages\Settings\TaxSystem::class,
                'purchase-pricing' => \App\Filament\Pages\Settings\PurchasePricing::class,
                'ai-configuration' => \App\Filament\Pages\Settings\AiConfiguration::class,
                'ai-enrichment-logs' => \App\Filament\Pages\Settings\AiEnrichmentLogs::class,
                'universal-printing' => \App\Filament\Pages\Settings\UniversalPrinting::class,
                'system' => \App\Filament\Pages\Settings\System::class,
                'roles-permissions' => \App\Filament\Pages\Settings\RolesPermissions::class,
                'users' => \App\Filament\Pages\Settings\Users::class,
                'system-backups' => \App\Filament\Pages\Settings\SystemBackups::class,
            ],
        ],
        'documentation' => [
            'label' => 'Documentation',
            'icon' => \Filament\Support\Icons\Heroicon::OutlinedBookOpen,
            'sort' => 110,
            'submenus' => [
                'user-guide' => 'User Guide',
                'api-docs' => 'API Docs',
                'changelog' => 'Changelog',
                'support' => 'Support',
            ],
            'submenu_icons' => [
                'user-guide' => \Filament\Support\Icons\Heroicon::OutlinedBookOpen,
                'api-docs' => \Filament\Support\Icons\Heroicon::OutlinedCodeBracket,
                'changelog' => \Filament\Support\Icons\Heroicon::OutlinedClipboardDocumentList,
                'support' => \Filament\Support\Icons\Heroicon::OutlinedLifebuoy,
            ],
        ],
    ],

];
